apiVersion: v1
kind: PersistentVolume
metadata:
  name: model
  namespace: spring-cloud-demo
  labels:
    pv: model1
spec:
  storageClassName: ml
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /Users/xiechunyong/data/nfs_data/apollo
    server: 192.168.3.53
  #volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model
  namespace: spring-cloud-demo
spec:
  storageClassName: ml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  
  selector:
    matchLabels:
      pv: model1

