apiVersion: v1
kind: PersistentVolume # ①
metadata:
  name: nfspv # ②
spec:
  mountOptions:
    - nfsvers=3
    - nolock
  capacity:
    storage: 10Gi # ③
  accessModes:
    - ReadWriteOnce # ④
  persistentVolumeReclaimPolicy: Recycle # ⑤
  storageClassName: nfs # ⑥
  nfs:
    path: /var/share/test # ⑦
    server: 47.114.90.75 # ⑧
