apiVersion: v1
kind: PersistentVolume # ①
metadata:
  name: nfspv # ②
spec:
  mountOptions:
    - nfsvers=3
    - nolock
  capacity:
    storage: 10Gi # ③
  accessModes:
    - ReadWriteOnce # ④
  persistentVolumeReclaimPolicy: Recycle # ⑤
  storageClassName: nfs # ⑥
  nfs:
    path: /nfsdata/test # ⑦
    server: 192.168.0.4 # ⑧
