apiVersion: v1
kind: PersistentVolume # ①
metadata:
  name: zookeeper-pv # ②
spec:
  mountOptions:
    - nfsvers=3
    - nolock
  capacity:
    storage: 3Gi # ③
  accessModes:
    - ReadWriteOnce # ④
  persistentVolumeReclaimPolicy: Recycle # ⑤
  storageClassName: zookeeper-nfs # ⑥
  nfs:
    path: /var/share/zookeeper # ⑦
    server: 47.114.90.75 # ⑧
