apiVersion: v1
kind: PersistentVolumeClaim # ①
metadata:
  namespace: spring-cloud-demo
  name: zookeeper-pvc # ②
spec:
  accessModes:
    - ReadWriteOnce # ③
  resources:
    requests:
      storage: 6Gi # ④
  storageClassName: zookeeper-nfs # ⑤
