# 外部访问服务
apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-demo
  name: jpa
  labels:
    app: jpa
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
      nodePort: 8000
  type: NodePort
  selector:
    app: jpa
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: spring-cloud-demo
  name: jpa
spec:
  serviceName: jpa
  replicas: 1
  template:
    metadata:
      labels:
        app: jpa
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: jpa
          imagePullPolicy: IfNotPresent
          image: xiechunyong/jpa
          resources:
            limits:
              memory: "1Gi"
              cpu: 500m
          ports:
            - containerPort: 8000
              name: client
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx512m -Dspring.profiles.active=test -Dspring.cloud.sentinel.transport.dashboard=sentinel:8858"
  selector:
    matchLabels:
      app: jpa