# 外部访问服务
apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-demo
  name: spring-cloud-sentinel-sample
  labels:
    app: spring-cloud-sentinel-sample
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8001
      targetPort: 8001
      nodePort: 18001
  type: NodePort
  selector:
    app: spring-cloud-sentinel-sample
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: spring-cloud-demo
  name: spring-cloud-sentinel-sample
spec:
  serviceName: spring-cloud-sentinel-sample
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-sentinel-sample
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: spring-cloud-sentinel-sample
          imagePullPolicy: IfNotPresent
          image: xiechunyong/spring-cloud-sentinel-sample
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8001
              name: client
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: "-Dserver=nacos.spring-cloud-demo:8848 -Dsentinel=sentinel.spring-cloud-demo:8858"
  selector:
    matchLabels:
      app: spring-cloud-sentinel-sample