apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: spring-cloud-demo
data:
  mysql.host: "sh-cynosdbmysql-grp-azoyq6z8.sql.tencentcdb.com"
  mysql.db.name: "nacos"
  mysql.port: "25388"
  mysql.user: "root"
  mysql.password: "Root123456"
