kind: Endpoints
apiVersion: v1
metadata:
  namespace: spring-cloud-demo
  name: nacos
  labels:
    app: nacos
subsets:
  - addresses:
      - ip: 180.76.150.171
    ports:
      - port: 8848
---
kind: Service
apiVersion: v1
metadata:
  namespace: spring-cloud-demo
  name: nacos
  labels:
    app: nacos
spec:
  ports:
  type: ClusterIP
  ports:
    - port: 8848
      targetPort: 8848