apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: spring-cloud-demo
spec:
  serviceName: nacos
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server
          ports:
            - containerPort: 8848
          env:
            - name: MYSQL_DATABASE_NUM
              value: "0"
            - name: MODE
              value: "standalone"
  selector:
    matchLabels:
      app: nacos
---
apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-demo
  name: nacos
  labels:
    name: nacos
spec:
  type: NodePort
  ports:
  - port: 8848
    protocol: TCP
    targetPort: 8848
    nodePort: 8848
  selector:
    app: nacos