apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: spring-cloud-demo
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.6.2
        imagePullPolicy: IfNotPresent
        env:  ###非常重要!!!服务之间ip动态变化, 配置连接最好用域名, Service域名规则是:service.namespace
        - name: ELASTICSEARCH_HOSTS  ###非常重要!!!注意是ELASTICSEARCH_HOSTS还是ELASTICSEARCH_URL, 得和当前版本kibana中/usr/share/kibana/config/kibana.yml的参数名称一样, 可以docker启动镜像进去看看
          value: "http://elasticsearch.spring-cloud-demo:9200"
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        ports:
        - name: ui
          containerPort: 5601
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: spring-cloud-demo
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 5601
  selector:
    app: kibana