kind: Service
apiVersion: v1
metadata:
  labels:
    app: db-mysql
  name: mysql-db-svc
  namespace: spring-cloud-demo
spec:
  type: NodePort
  selector:
    app: db-mysql
  ports:
    - name: tcp-3306
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 3306
