apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: spring-cloud-demo
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: spring-cloud-demo
subsets:
- addresses:
  - ip: 192.168.3.53
  ports:
  - name: mysql
    port: 3306
    protocol: TCP