kind: Endpoints
apiVersion: v1
metadata:
  namespace: spring-cloud-demo
  name: mysql
  labels:
    app: mysql
subsets:
  - addresses:
      # - ip: 192.168.3.53
      - ip: 192.168.43.45
    ports:
      - port: 3306
---
kind: Service
apiVersion: v1
metadata:
  namespace: spring-cloud-demo
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306