apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spring-cloud-demo
  name: mysql-claim
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
