apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-cloud-demo
  name: xxl-job-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - name: xxl-job-admin
        image: xuxueli/xxl-job-admin:2.3.1 # 使用2.3.1版本
        imagePullPolicy: Always     # 优先使用本地镜像
        ports:
        - containerPort: 8080
        env:
        - name: PARAMS   # 定义变量，用来设定mysql的用户/密码 mysql为k8s集群内的service名称，在k8s集群内部可以直接使用service名称，使用时mail替换成自己的邮箱和密码
          value: "--spring.datasource.url=jdbc:mysql://47.118.249.158:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=root --spring.datasource.password=Root123456 --spring.mail.username=328029993@qq.com --spring.mail.password=aizdqtpccbcncagb"
---
apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-demo
  name: xxl-job-admin
  labels:
    app: xxl-job-admin
spec:
  ports:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 10859 # nodeport映射到本机的8080端口
  selector:
    app: xxl-job-admin