---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /nfsdata/redis
    server: 192.168.64.6


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs

---
apiVersion: v1
data:
  redis.conf: |
    appendonly yes
kind: ConfigMap
metadata:
  name: redis-conf

---
apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-demo
  name: redis
  labels:
    name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 6379
  type: NodePort

--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: spring-cloud-demo
  labels:
    app: redis
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command:
          - redis-server
          - "/redis-master/redis.conf"  #指的是redis容器内部的位置
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        - mountPath: /redis-master
          name: redis-conf
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: pvc-redis
        - name: redis-conf
          configMap:
            name: redis-conf
            items:
            - key: redis.conf
              path: redis.conf
